[package]
name = "discord-gouda-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gouda = "0.2.0-alpha"
